doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            project_id: DomainDrivers\SmartSchedule\Planning\Infrastructure\ProjectIdType
            parallel_stages_list: DomainDrivers\SmartSchedule\Planning\Infrastructure\ParallelStagesListType
            schedule: DomainDrivers\SmartSchedule\Planning\Infrastructure\ScheduleType
            demands: DomainDrivers\SmartSchedule\Planning\Infrastructure\DemandsType
            demands_per_stage: DomainDrivers\SmartSchedule\Planning\Infrastructure\DemandsPerStageType
            chosen_resources: DomainDrivers\SmartSchedule\Planning\Infrastructure\ChosenResourcesType
            project_allocations_id: DomainDrivers\SmartSchedule\Allocation\Infrastructure\ProjectAllocationsIdType
            allocation_demands: DomainDrivers\SmartSchedule\Allocation\Infrastructure\DemandsType
            allocations: DomainDrivers\SmartSchedule\Allocation\Infrastructure\AllocationsType
            cost: DomainDrivers\SmartSchedule\Allocation\Cashflow\Infrastructure\CostType
            earnings: DomainDrivers\SmartSchedule\Allocation\Cashflow\Infrastructure\EarningsType
            income: DomainDrivers\SmartSchedule\Allocation\Cashflow\Infrastructure\IncomeType
            capabilities: DomainDrivers\SmartSchedule\Shared\Infrastructure\CapabilitiesType
            capability: DomainDrivers\SmartSchedule\Shared\Infrastructure\CapabilityType
            device_id: DomainDrivers\SmartSchedule\Resource\Device\Infrastructure\DeviceIdType
            employee_id: DomainDrivers\SmartSchedule\Resource\Employee\Infrastructure\EmployeeIdType
            allocatable_resource_id: DomainDrivers\SmartSchedule\Allocation\CapabilityScheduling\Infrastructure\AllocatableResourceIdType
            allocatable_capability_id: DomainDrivers\SmartSchedule\Allocation\CapabilityScheduling\Infrastructure\AllocatableCapabilityIdType
            capability_selector: DomainDrivers\SmartSchedule\Allocation\CapabilityScheduling\Infrastructure\CapabilitySelectorType
        schema_filter: '~^(?!availabilities)~'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
            string_functions:
                JSONB_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonbContains
        mappings:
            Planning:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/SmartSchedule/Planning'
                prefix: 'DomainDrivers\SmartSchedule\Planning'
                alias: Planning
            Allocation:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/SmartSchedule/Allocation'
                prefix: 'DomainDrivers\SmartSchedule\Allocation'
                alias: Allocation
            Resource:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/SmartSchedule/Resource'
                prefix: 'DomainDrivers\SmartSchedule\Resource'
                alias: Resource
            Shared:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/SmartSchedule/Shared'
                prefix: 'DomainDrivers\SmartSchedule\Shared'
                alias: Shared
        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
