doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            project_id: DomainDrivers\SmartSchedule\Planning\Infrastructure\ProjectIdType
            parallel_stages_list: DomainDrivers\SmartSchedule\Planning\Infrastructure\ParallelStagesListType
            schedule: DomainDrivers\SmartSchedule\Planning\Infrastructure\ScheduleType
            demands: DomainDrivers\SmartSchedule\Planning\Infrastructure\DemandsType
            demands_per_stage: DomainDrivers\SmartSchedule\Planning\Infrastructure\DemandsPerStageType
            chosen_resources: DomainDrivers\SmartSchedule\Planning\Infrastructure\ChosenResourcesType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/SmartSchedule/Planning'
                prefix: 'DomainDrivers\SmartSchedule\Planning'
                alias: Planning
        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
