framework:
    messenger:
        buses:
            event:
                default_middleware:
                    allow_no_handlers: true
        transports:
            event: 'sync://'

        routing:
            'DomainDrivers\SmartSchedule\*': event

when@test:
    framework:
        messenger:
            transports:
                event: 'test://'
